
    <option value="Aileu">Aileu</option>
    <option value="Ainaro">Ainaro</option>
    <option value="Baucau">Baucau</option>
    <option value="Bobonaro">Bobonaro</option>
    <option value="Cova Lima">Cova Lima</option>
    <option value="Díli">Díli</option>
    <option value="Ermera">Ermera</option>
    <option value="Lautém">Lautém</option>
    <option value="Liquiça">Liquiça</option>
    <option value="Manatuto">Manatuto</option>
    <option value="Manufahi">Manufahi</option>
    <option value="Oe-Cusse">Oe-Cusse</option>
   <!-- <option value="Minas Gerais">Minas Gerais</option>
    <option value="Pará">Pará</option>
    <option value="Paraíba">Paraíba</option>
    <option value="Paraná">Paraná</option>
    <option value="Pernambuco">Pernambuco</option>
    <option value="Piauí">Piauí</option>
    <option value="Rio de Janeiro">Rio de Janeiro</option>
    <option value="Rio Grande do Norte">Rio Grande do Norte</option>
    <option value="Rio Grande do Sul">Rio Grande do Sul</option>
    <option value="Rondônia">Rondônia</option>
    <option value="Roraima">Roraima</option>
    <option value="Santa Catarina">Santa Catarina</option>
    <option value="São Paulo">São Paulo</option>
    <option value="Sergipe">Sergipe</option>
    <option value="Tocantins">Tocantins</option>-->
    <option value="Estrangeiro">Estrangeiro</option>