
					<option value="BRASIL" selected="selecte">BRASIL</option>
					<option value="AFEGANISTAO">AFEGANISTAO</option>
					<option value="AFRICA DO SUL">AFRICA DO SUL</option>
					<option value="ALASCA">ALASCA</option>
					<option value="ALBANIA">ALBANIA</option>
					<option value="ALEMANHA">ALEMANHA</option>
					<option value="ANDORRA">ANDORRA</option>
					<option value="ANGOLA">ANGOLA</option>
					<option value="ANGUILLA">ANGUILLA</option>
					<option value="ANT. HOLANDESAS">ANT.HOLANDESAS</option>
					<option value="ANTIGUA">ANTIGUA</option>
					<option value="ARABIAAUDITA">ARABIAAUDITA</option>
					<option value="ARGELIA">ARGELIA</option>
					<option value="ARGENTINA">ARGENTINA</option>
					<option value="ARMENIA">ARMENIA</option>
					<option value="ARUBA">ARUBA</option>
					<option value="ASCENSAO ILHAS">ASCENSAO ILHAS</option>
					<option value="AUSTRALIA">AUSTRALIA</option>
					<option value="AUSTRIA">AUSTRIA</option>
					<option value="AZERBAIJAO">AZERBAIJAO</option>
					<option value="BAHAMAS">BAHAMAS</option>
					<option value="BANGLADESH">BANGLADESH</option>
					<option value="BARBADOS">BARBADOS</option>
					<option value="BAREIN">BAREIN</option>
					<option value="BELARUS">BELARUS</option>
					<option value="BELGICA">BELGICA</option>
					<option value="BELIZE">BELIZE</option>
					<option value="BENIN">BENIN</option>
					<option value="BERMUDAS">BERMUDAS</option>
					<option value="BOLIVIA">BOLIVIA</option>
					<option value="BOSNIA E HERZEGOVINA">BOSNIA E HERZEGOVINA</option>
					<option value="BOTSUANA">BOTSUANA</option>
					<option value="BRUNEI">BRUNEI</option>
					<option value="BULGARIA">BULGARIA</option>
					<option value="BURKINA FASO">BURKINA FASO</option>
					<option value="BURUNDI">BURUNDI</option>
					<option value="BUTAO">BUTAO</option>
					<option value="CABO VERDE">CABO VERDE</option>
					<option value="CAMAROES">CAMAROES</option>
					<option value="CAMPUCHEA">CAMPUCHEA</option>
					<option value="CANADA">CANADA</option>
					<option value="CASAQUISTAO">CASAQUISTAO</option>
					<option value="CATAR">CATAR</option>
					<option value="CAYMAN ILHAS">CAYMAN ILHAS</option>
					<option value="CHADE">CHADE</option>
					<option value="CHILE">CHILE</option>
					<option value="CHINA">CHINA</option>
					<option value="CHIPRE">CHIPRE</option>
					<option value="CINGAPURA">CINGAPURA</option>
					<option value="COLOMBIA">COLOMBIA</option>
					<option value="COMORES">COMORES</option>
					<option value="CONGO">CONGO</option>
					<option value="COOK ILHAS">COOK ILHAS</option>
					<option value="COREIA DO NORTE">COREIA DO NORTE</option>
					<option value="COREIA DO SUL">COREIA DO SUL</option>
					<option value="COSTA DO MARFIM">COSTA DO MARFIM</option>
					<option value="COSTA RICA">COSTA RICA</option>
					<option value="CROACIA">CROACIA</option>
					<option value="CUBA">CUBA</option>
					<option value="DIEGO GARCIA">DIEGO GARCIA</option>
					<option value="DINAMARCA">DINAMARCA</option>
					<option value="DJIBUTI">DJIBUTI</option>
					<option value="DOMINICA">DOMINICA</option>
					<option value="DOMINICANA REP">DOMINICANA REP</option>
					<option value="EGITO">EGITO</option>
					<option value="ELALVADOR">ELALVADOR</option>
					<option value="EMIRADOS A. UNIDOS">EMIRADOS A. UNIDOS</option>
					<option value="EQUADOR">EQUADOR</option>
					<option value="ERITREA">ERITREA</option>
					<option value="ESLOVENIA">ESLOVENIA</option>
					<option value="ESPANHA">ESPANHA</option>
					<option value="ESTADOS UNIDOS">ESTADOS UNIDOS</option>
					<option value="ESTONIA">ESTONIA</option>
					<option value="ETIOPIA">ETIOPIA</option>
					<option value="FAROE ILHAS">FAROE ILHAS</option>
					<option value="FIJI">FIJI</option>
					<option value="FILIPINAS">FILIPINAS</option>
					<option value="FINLANDIA">FINLANDIA</option>
					<option value="FORMOSA">FORMOSA</option>
					<option value="FRANCA">FRANCA</option>
					<option value="GABAO">GABAO</option>
					<option value="GAMBIA">GAMBIA</option>
					<option value="GANA">GANA</option>
					<option value="GEORGIA">GEORGIA</option>
					<option value="GIBRALTAR">GIBRALTAR</option>
					<option value="GRANADA">GRANADA</option>
					<option value="GRECIA">GRECIA</option>
					<option value="GROENLANDIA">GROENLANDIA</option>
					<option value="GUADALUPE">GUADALUPE</option>
					<option value="GUAM">GUAM</option>
					<option value="GUATEMALA">GUATEMALA</option>
					<option value="GUIANA">GUIANA</option>
					<option value="GUIANA FRANCESA">GUIANA FRANCESA</option>
					<option value="GUINE">GUINE</option>
					<option value="GUINE EQUATORIAL">GUINE EQUATORIAL</option>
					<option value="GUINE BISSAU">GUINE BISSAU</option>
					<option value="HAITI">HAITI</option>
					<option value="HAVAI">HAVAI</option>
					<option value="HOLANDA">HOLANDA</option>
					<option value="HONDURAS">HONDURAS</option>
					<option value="HONG KONG">HONG KONG</option>
					<option value="HUNGRIA">HUNGRIA</option>
					<option value="IEMEN REP. ">IEMEN REP.</option>
					<option value="INDIA">INDIA</option>
					<option value="INDONESIA">INDONESIA</option>
					<option value="IRA">IRA</option>
					<option value="IRAQUE">IRAQUE</option>
					<option value="IRLANDA">IRLANDA</option>
					<option value="ISLANDIA">ISLANDIA</option>
					<option value="ISRAEL">ISRAEL</option>
					<option value="ITALIA">ITALIA</option>
					<option value="JAMAICA">JAMAICA</option>
					<option value="JAPAO">JAPAO</option>
					<option value="JORDANIA">JORDANIA</option>
					<option value="KIRIBATI">KIRIBATI</option>
					<option value="KUWEIT">KUWEIT</option>
					<option value="LAOS">LAOS</option>
					<option value="LESOTO">LESOTO</option>
					<option value="LETONIA">LETONIA</option>
					<option value="LIBANO">LIBANO</option>
					<option value="LIBERIA">LIBERIA</option>
					<option value="LIBIA">LIBIA</option>
					<option value="LIECHTENSTEIN">LIECHTENSTEIN</option>
					<option value="LITUANIA">LITUANIA</option>
					<option value="LUXEMBURGO">LUXEMBURGO</option>
					<option value="MACAU">MACAU</option>
					<option value="MACEDONIA">MACEDONIA</option>
					<option value="MADAGASCAR">MADAGASCAR</option>
					<option value="MALASIA">MALASIA</option>
					<option value="MALAVI">MALAVI</option>
					<option value="MALDIVAS">MALDIVAS</option>
					<option value="MALI">MALI</option>
					<option value="MALTA">MALTA</option>
					<option value="MALVINAS ILHAS">MALVINAS ILHAS</option>
					<option value="MARIANASORTE ISL. ">MARIANASORTE ISL.</option>
					<option value="MARROCOS">MARROCOS</option>
					<option value="MARSHALL ILHAS">MARSHALL ILHAS</option>
					<option value="MARTINICA">MARTINICA</option>
					<option value="MAURICIO">MAURICIO</option>
					<option value="MAURITANIA">MAURITANIA</option>
					<option value="MAYOTTE(ILHAS)">MAYOTTE(ILHAS)</option>
					<option value="MEXICO">MEXICO</option>
					<option value="MICRONESIA">MICRONESIA</option>
					<option value="MIDWAY ILHAS">MIDWAY ILHAS</option>
					<option value="MOCAMBIQUE">MOCAMBIQUE</option>
					<option value="MOLDOVA">MOLDOVA</option>
					<option value="MONGOLIA">MONGOLIA</option>
					<option value="MONTENEGRO">MONTENEGRO</option>
					<option value="MONTSERRAT">MONTSERRAT</option>
					<option value="NAMIBIA">NAMIBIA</option>
					<option value="NAURU">NAURU</option>
					<option value="NEPAL">NEPAL</option>
					<option value="NICARAGUA">NICARAGUA</option>
					<option value="NIGER">NIGER</option>
					<option value="NIGERIA">NIGERIA</option>
					<option value="NIUE">NIUE</option>
					<option value="NORFOLK ILHA">NORFOLK ILHA</option>
					<option value="NORUEGA">NORUEGA</option>
					<option value="NOVA CALEDONIA">NOVA CALEDONIA</option>
					<option value="NOVA ZELANDIA">NOVA ZELANDIA</option>
					<option value="OMA">OMA</option>
					<option value="PALAU">PALAU</option>
					<option value="PALESTINA">PALESTINA</option>
					<option value="PANAMA">PANAMA</option>
					<option value="PAPUAOVA GUINE">PAPUAOVA GUINE</option>
					<option value="PAQUISTAO">PAQUISTAO</option>
					<option value="PARAGUAI">PARAGUAI</option>
					<option value="PERU">PERU</option>
					<option value="POLONIA">POLONIA</option>
					<option value="PORTO RICO">PORTO RICO</option>
					<option value="PORTUGAL">PORTUGAL</option>
					<option value="PRINCIPADO MONACO">PRINCIPADO MONACO</option>
					<option value="QUENIA">QUENIA</option>
					<option value="QUIRGUIZIA">QUIRGUIZIA</option>
					<option value="REINO UNIDO">REINO UNIDO</option>
					<option value="REP. CENTRO AFRICANA">REP.CENTRO AFRICANA</option>
					<option value="REP. ESLOVAQUIA">REP.ESLOVAQUIA</option>
					<option value="REP. TCHECA">REP.TCHECA</option>
					<option value="REUNIAO ILHAS">REUNIAO ILHAS</option>
					<option value="RODRIGUES ILHAS">RODRIGUES ILHAS</option>
					<option value="ROMENIA">ROMENIA</option>
					<option value="RUANDA">RUANDA</option>
					<option value="RUSSIA">RUSSIA</option>
					<option value="S. KITTS &amp; NEVIS">S.KITTS &amp; NEVIS</option>
					<option value="S. VICENTE ILHAS">S.VICENTE ILHAS</option>
					<option value="SAARA ESPANHOL">SAARA ESPANHOL</option>
					<option value="SALOMAO ILHAS">SALOMAO ILHAS</option>
					<option value="SAMOA">SAMOA</option>
					<option value="SAMOA AMERICANA">SAMOA AMERICANA</option>
					<option value="SANTA LUCIA">SANTA LUCIA</option>
					<option value="SAO MARINO">SAO MARINO</option>
					<option value="SAO TOME E PRINCIPE">SAO TOME E PRINCIPE</option>
					<option value="SENEGAL">SENEGAL</option>
					<option value="SERRA LEOA">SERRA LEOA</option>
					<option value="SÉRVIA">SÉRVIA</option>
					<option value="SEYCHELLES">SEYCHELLES</option>
					<option value="SIRIA">SIRIA</option>
					<option value="SOMALIA">SOMALIA</option>
					<option value="SRI LANKA">SRI LANKA</option>
					<option value="ST. PIERRE E MIQUELON">ST.PIERRE E MIQUELON</option>
					<option value="STA HELENA ILHAS">STA HELENA ILHAS</option>
					<option value="SUAZILANDIA">SUAZILANDIA</option>
					<option value="SUDAO">SUDAO</option>
					<option value="SUECIA">SUECIA</option>
					<option value="SUICA">SUICA</option>
					<option value="SURINAME">SURINAME</option>
					<option value="TADJIQUISTAO">TADJIQUISTAO</option>
					<option value="TAILANDIA">TAILANDIA</option>
					<option value="TAITI">TAITI</option>
					<option value="TANZANIA">TANZANIA</option>
					<option value="TERRIT. EXT. AUSTRALIA">TERRIT.EXT.AUSTRALIA</option>
					<option value="TIMOR LESTE">TIMOR-LESTE</option>
					<option value="TOGO">TOGO</option>
					<option value="TONGA">TONGA</option>
					<option value="TOQUELAU">TOQUELAU</option>
					<option value="TRINIDAD E TOBAGO">TRINIDAD E TOBAGO</option>
					<option value="TUNISIA">TUNISIA</option>
					<option value="TURCOMENIA">TURCOMENIA</option>
					<option value="TURKS E CAICOS ILHAS">TURKS E CAICOS ILHAS</option>
					<option value="TURQUIA">TURQUIA</option>
					<option value="TUVALU">TUVALU</option>
					<option value="UCRANIA">UCRANIA</option>
					<option value="UGANDA">UGANDA</option>
					<option value="UNIAO DE MYANMAR">UNIAO DE MYANMAR</option>
					<option value="URUGUAI">URUGUAI</option>
					<option value="UZBEQUISTAO">UZBEQUISTAO</option>
					<option value="VANUATU">VANUATU</option>
					<option value="VENEZUELA">VENEZUELA</option>
					<option value="VIETNA">VIETNA</option>
					<option value="VIRGENS A. ILHAS">VIRGENS A. ILHAS</option>
					<option value="VIRGENS B. ILHAS">VIRGENS B.ILHAS</option>
					<option value="WAKE ILHAS">WAKE ILHAS</option>
					<option value="WALLIS E FUTUNA">WALLIS E FUTUNA</option>
					<option value="ZAIRE">ZAIRE</option>
					<option value="ZAMBIA">ZAMBIA</option>
					<option value="ZANZIBAR">ZANZIBAR</option>
					<option value="ZIMBABUE">ZIMBABUE</option>
